# SwiftLint Configuration for Triangulum

# Disabled Rules
disabled_rules:
  - todo
  - trailing_whitespace
  - vertical_whitespace

# Customizable Rules
line_length:
  warning: 200
  error: 200
  ignores_function_declarations: true
  ignores_comments: true

identifier_name:
  excluded:
    - x
    - y
    - z
    - r
    - i
    - j
    - k
    - n
    - t
    - a
    - b
    - c
    - d
    - f
    - g
    - h
    - l
    - m
    - p
    - s
    - D
    - F
    - L
    - M
    - az
    - eq
    - jd
    - pt
    - ra
    - sy
    - vx
    - vy
    - xe
    - xg
    - ye
    - yg
    - ze
    - zg
    - Lp
    - Mp
    - fg
    - pa
    - pb
    - sx
    - u1
    - u2
    - id
    - mu
    - j2
    - ma
    - a1
    - e2

function_body_length:
  warning: 100
  error: 200

type_body_length:
  warning: 700
  error: 700

file_length:
  warning: 900
  error: 900

function_parameter_count:
  warning: 10
  error: 10

large_tuple:
  warning: 3
  error: 5

nesting:
  type_level:
    warning: 2
    error: 3

# Exclude paths
excluded:
  - Pods
